vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    adds:
      uri_prefix: /images/adds
      upload_destination: "%kernel.project_dir%/public/images/adds"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true
      delete_on_remove: true
